name: MMOCore
main: cn.whiteg.mmocore.MMOCore
version: 1.1
author: MoeWhite
softdepend: []
commands:
  mmocore:
    description: The is MMOCore
    aliases: ['mmo','mmc','moc','mmoc']
  userdata:
    description: The is MMOCore
    aliases: ['ud','usd']
  confirm:
    description: Confirm
    aliases: ['cf','c']
  deny:
    description: Confirm
    aliases: ['d','dy']
