ver: 6
debug: false
#玩家退出清理数据缓存
QuitDeleteCache: false
#数据储存文件夹
DataDir: "plugins/MMOCore/Player"
#防止玩家操作过于频繁
Frequently: false
#服务器是否是在线模式
Online_Mode: false

#玩家请求提示音 - 列表播放
PlayerReqestSound:
  #循环播放
  loop: false
  #tick帧间隔
  tick: 2
  #音轨(可嵌套List实现同轨多音符)
  track:
    - 'block.note_block.bell 1 0'
    - 'block.note_block.bell 1 0.1'
    - 'block.note_block.bell 1 0.15'
    - ''
    - ''
    - ''
    - ''
    #同轨多符号
    - - 'block.note_block.bell 1 1'
      - 'block.note_block.bit 1 1.2'

#玩家请求提示音 - 同轨播放
#PlayerReqestSound:
  - 'block.note_block.bell 1 0'
  - 'block.note_block.bell 1 0.1'
  - 'block.note_block.bell 1 0.15'

#玩家请求提示音 - 单个音效
#PlayerReqestSound: 'block.note_block.bell 1 0 Player'


#最近玩家列表最大数量(用于部分指令的Tab补全显示最近上线过的离线玩家)
LatelyPlayerListSize: 50